### PR TITLE
Replace MaterialApp as a root Widget by a builder

### PR DESCRIPTION
**Pull request by jakobleck**
Instead of letting the AppLock widget create a fixed MaterialApp, I suggest to pass a builder function to the AppLock constructor such that a user can customize their root widget, like a MaterialApp (or, in the context I wanted to use the package, a GetMaterialApp from the get package, which was not compatible with the flutter_app_lock package in its current form).
The user has to pass the arguments of the builder to his root widget, e.g. as in
```
appBuilder: (navigatorKey, initialRoute, routes) => MaterialApp(
            debugShowCheckedModeBanner: false,
            navigatorKey: navigatorKey,
            routes: routes,
            initialRoute: initialRoute,
            theme: theme,
          )
```
and can then customize the root widget however he likes.

I have seen that there are already ambitions to replace the MaterialApp in AppLock, I add this PR as a suggestion, I think it might be a neat solution.

### CODE REVIEW

**Comment by tomalabaster** [comment]
Hi @jakobleck!

Firstly, thank you for your interest in using flutter_app_lock! I really appreciate you using it and finding ways to improve it.

I've actually got a release primed and ready which removes the use of `MaterialApp` entirely. You can find it here:
- [Branch on Github](https://github.com/tomalabaster/flutter_app_lock/tree/release/4.0.0-dev.0)
- [Release on pub.dev](https://pub.dev/packages/flutter_app_lock/versions/4.0.0-dev.0)

I'd be interested in you trying out the 4.0.0-dev.0 release and seeing how that works in your scenario. As far as I can see, `GetMaterialApp` also has a `builder` property which should make 4.0.0-dev.0 compatible.

**Comment by tomalabaster** [comment]
No problem at all @jakobleck! Sure, I think I follow. Let me know how you get on. If 4.0.0-dev.0 is suitable for you, I've had confirmation from someone else that it's all good for them as well so I'll then migrate 4.0.0-dev.0 to a standard 4.0.0 release :+1:

**Comment by jakobleck** [comment]
So I had another look at it and it seems that the 4.0.0-dev.0 is indeed suitable for what I'm doing. I added a
```
builder: (context, child) => AppLock(
        builder: (context, args) => child!,
        lockScreen: ScreenLockPage(
          onAuthenticate: (context) => AppLock.of(context)!.didUnlock(),
        ),
        enabled: needsAuthentication,
      ),
```
to the `GetMaterialApp` that is my root widget and things work. 

Not everything works right away: In the lockscreen widget's controller `Get.dialog()`doesn't work, for example, but there are workarounds (passing the BuildContext to the controller from the UI to use the normal showDialog instead), and I'd put the blame on the peculiarities of the get package.

For the concrete usecase with the get package my solution seems simpler in one or two places from what I've seen so far, but the 4.0.0-dev.0 solves my problem as well, so I'll use that and close the PR.

**Comment by jakobleck** [comment]
Called it too soon, maybe. Because of https://github.com/tomalabaster/flutter_app_lock/issues/26 my PR might actually be a good alternative.

**Pull request closed without merging**
