### PR TITLE
Expose showLock

### PR DESCRIPTION
**Pull request by rdev-software**
to be able to call AppLock manually

### CODE REVIEW

**Comment by tomalabaster** [comment]
Thank you for the PR!

Happy for this to come in. Could I ask though that you move the `showLockScreen` method to just after the `disable` method, and add a basic documentation header like the other public methods?

It can say something simple along the lines of `Manually show the [lockScreen].`

**Comment by tomalabaster** [comment]
I'm going to merge this in and add the documentation header, then will release on pub.dev. Thank you!

**Comment by rdev-software** [comment]
Sure, sorry that I didnt reply...I was bit busy and I planned to do other stuff with it. But I didnt have to finish it. Anyway thank you for accepting it

**Comment by tomalabaster** [comment]
That's ok! I've published the update on pub.dev. I've also made the method return a `Future` so it can be awaited.

**Pull request merged**
